### ISSUE TITLE
Request: Exclude calendar 

### ISSUE THREAD

**Issue by P8DFxKfyJB** [drewkerr/scriptable#1]
I have a lot of calendars in the calendar app. Some of them I want to exclude in the widget. How can I do that?
Thanks a lot in advance.

![Bild-3](https://user-images.githubusercontent.com/32517263/96525577-941ae500-127b-11eb-82fe-46ea3b4b2df7.jpg)

**Comment by drewkerr** [comment]
I've updated the code with optional configuration. Edit the code to specify calendars.

**Comment by P8DFxKfyJB** [comment]
Thank you. 👍🏻
