### ISSUE TITLE
Error on line 269: SyntaxError: Unexpected identifier 'loadData'. Expected ';' after variable declaration.

### ISSUE THREAD

**Issue by seanob86** [drewkerr/scriptable#2]
Running latest script without making any changes returns this error.

`Error on line 269: SyntaxError: Unexpected identifier 'loadData'. Expected ';' after variable declaration.`

**Comment by matbor** [comment]
+1 same.

**Comment by drewkerr** [comment]
Try the updated code - works for me.

**Comment by matbor** [comment]
Works now, thanks 🙏
